In [1]:
#Basic libraries
import pandas as pd 
import numpy as np 

#Visualization libraries
import matplotlib.pyplot as plt 
from matplotlib import rcParams
import seaborn as sns
from textblob import TextBlob
from plotly import tools
import plotly.graph_objs as go
from plotly.offline import iplot
%matplotlib inline
plt.rcParams['figure.figsize'] = [10, 5]
import cufflinks as cf
cf.go_offline()
cf.set_config_file(offline=False, world_readable=True)

#NLTK libraries
import nltk
import re
import string
from nltk.corpus import stopwords
from wordcloud import WordCloud,STOPWORDS
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
# Machine Learning libraries
import sklearn 
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
 

#Metrics libraries
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

#Miscellanous libraries
from collections import Counter

#Ignore warnings
import warnings
warnings.filterwarnings('ignore')

#Deep learning libraries
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [50]:
#reading the fake and true datasets
fake_news = pd.read_csv('/Fake.csv')
true_news = pd.read_csv('/True.csv')

# print shape of fake dataset with rows and columns and information 
print ("The shape of the  data is (row, column):"+ str(fake_news.shape))
print (fake_news.info())
print("\n --------------------------------------- \n")

# print shape of true dataset with rows and columns and information
print ("The shape of the  data is (row, column):"+ str(true_news.shape))
print (true_news.info())

The shape of the  data is (row, column):(23481, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
dtypes: object(4)
memory usage: 733.9+ KB
None

 --------------------------------------- 

The shape of the  data is (row, column):(21417, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   title    21417 non-null  object
 1   text     21417 non-null  object
 2   subject  21417 non-null  object
 3   date     21417 non-null  object
dtypes: object(4)
memory usage: 669.4+ KB
None


In [51]:
#Target variable for fake news
fake_news['output']=0

#Target variable for true news
true_news['output']=1

In [4]:
#Concatenating and dropping for fake news
fake_news['news']=fake_news['title']+fake_news['text']
fake_news=fake_news.drop(['title', 'text'], axis=1)

#Concatenating and dropping for true news
true_news['news']=true_news['title']+true_news['text']
true_news=true_news.drop(['title', 'text'], axis=1)

#Rearranging the columns
fake_news = fake_news[['subject', 'date', 'news','output']]
true_news = true_news[['subject', 'date', 'news','output']]

In [5]:
fake_news['date'].value_counts()

May 10, 2017         46
May 6, 2016          44
May 5, 2016          44
May 26, 2016         44
May 11, 2016         43
                     ..
December 11, 2017     1
December 9, 2017      1
14-Feb-18             1
December 4, 2017      1
Jul 19, 2015          1
Name: date, Length: 1681, dtype: int64

In [6]:
#Removing links and the headline from the date column
fake_news=fake_news[~fake_news.date.str.contains("http")]
fake_news=fake_news[~fake_news.date.str.contains("HOST")]

'''You can also execute the below code to get the result 
which allows only string which has the months and rest are filtered'''
#fake_news=fake_news[fake_news.date.str.contains("Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec")]

'You can also execute the below code to get the result \nwhich allows only string which has the months and rest are filtered'

In [7]:
#Converting the date to datetime format
fake_news['date'] = pd.to_datetime(fake_news['date'])
true_news['date'] = pd.to_datetime(true_news['date'])

In [8]:
frames = [fake_news, true_news]
news_dataset = pd.concat(frames)
news_dataset

subject  ... output
0           News  ...      0
1           News  ...      0
2           News  ...      0
3           News  ...      0
4           News  ...      0
...          ...  ...    ...
21412  worldnews  ...      1
21413  worldnews  ...      1
21414  worldnews  ...      1
21415  worldnews  ...      1
21416  worldnews  ...      1

[44888 rows x 4 columns]

In [9]:
#Creating a copy 
clean_news=news_dataset.copy()
def review_cleaning(text):
    '''Make text lowercase, remove text in square brackets,remove links,remove punctuation
    and remove words containing numbers.'''
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    return clean_news['news'].apply(lambda x:review_cleaning(x))
clean_news.head()

subject       date                                               news  output
0    News 2017-12-31   Donald Trump Sends Out Embarrassing New Year’...       0
1    News 2017-12-31   Drunk Bragging Trump Staffer Started Russian ...       0
2    News 2017-12-30   Sheriff David Clarke Becomes An Internet Joke...       0
3    News 2017-12-29   Trump Is So Obsessed He Even Has Obama’s Name...       0
4    News 2017-12-25   Pope Francis Just Called Out Donald Trump Dur...       0

In [11]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [12]:
stop = stopwords.words('english')
clean_news['news'] = clean_news['news'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
clean_news.head()

subject       date                                               news  output
0    News 2017-12-31  Donald Trump Sends Out Embarrassing New Year’s...       0
1    News 2017-12-31  Drunk Bragging Trump Staffer Started Russian C...       0
2    News 2017-12-30  Sheriff David Clarke Becomes An Internet Joke ...       0
3    News 2017-12-29  Trump Is So Obsessed He Even Has Obama’s Name ...       0
4    News 2017-12-25  Pope Francis Just Called Out Donald Trump Duri...       0

In [17]:
#Extracting 'reviews' for processing
news_features=clean_news.copy()
news_features=news_features[['news']].reset_index(drop=True)
news_features.head()

news
0  Donald Trump Sends Out Embarrassing New Year’s...
1  Drunk Bragging Trump Staffer Started Russian C...
2  Sheriff David Clarke Becomes An Internet Joke ...
3  Trump Is So Obsessed He Even Has Obama’s Name ...
4  Pope Francis Just Called Out Donald Trump Duri...

In [19]:
stop_words = set(stopwords.words("english"))
#Performing stemming on the review dataframe
ps = PorterStemmer()

#splitting and adding the stemmed words except stopwords
corpus = []
for i in range(0, len(news_features)):
    news = re.sub('[^a-zA-Z]', ' ', news_features['news'][i])
    news= news.lower()
    news = news.split()

    news = ' '.join(news)
    corpus.append(news)#Getting the target variable
y=clean_news['output']

In [20]:
#Setting up vocabulary size
voc_size=10000

#One hot encoding 
onehot_repr=[one_hot(words,voc_size)for words in corpus]

In [22]:
#Setting sentence length
sent_length=5000

#Padding the sentences
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...   30 3659 1629]
 [   0    0    0 ... 1836 3659 1629]
 [   0    0    0 ... 7311 3659 1629]
 ...
 [   0    0    0 ... 3504 2187 2317]
 [   0    0    0 ... 6474 3636 5330]
 [   0    0    0 ... 5623 6552 1085]]


In [23]:
#Creating the lstm model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100)) #Adding 100 lstm neurons in the layer
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))

#Compiling the model
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 5000, 40)          400000    
_________________________________________________________________
dropout (Dropout)            (None, 5000, 40)          0         
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 456,501
Trainable params: 456,501
Non-trainable params: 0
_________________________________________________________________
None


In [24]:
# Converting the X and y as array
X_final=np.array(embedded_docs)
y_final=np.array(y)

#Check shape of X and y final
X_final.shape,y_final.shape

((44888, 5000), (44888,))

In [25]:
# Train test split of the X and y final
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

# Fitting with 10 epochs and 64 batch size
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
470/470 [==============================] - 161s 273ms/step - loss: 0.3106 - accuracy: 0.8897 - val_loss: 0.1227 - val_accuracy: 0.9594
Epoch 2/10
470/470 [==============================] - 128s 272ms/step - loss: 0.0641 - accuracy: 0.9796 - val_loss: 0.0859 - val_accuracy: 0.9750
Epoch 3/10
470/470 [==============================] - 126s 269ms/step - loss: 0.0293 - accuracy: 0.9917 - val_loss: 0.0244 - val_accuracy: 0.9945
Epoch 4/10
470/470 [==============================] - 125s 267ms/step - loss: 0.0152 - accuracy: 0.9958 - val_loss: 0.1111 - val_accuracy: 0.9599
Epoch 5/10
470/470 [==============================] - 129s 274ms/step - loss: 0.1014 - accuracy: 0.9624 - val_loss: 0.0746 - val_accuracy: 0.9802
Epoch 6/10
470/470 [==============================] - 128s 272ms/step - loss: 0.1409 - accuracy: 0.9544 - val_loss: 0.0945 - val_accuracy: 0.9713
Epoch 7/10
470/470 [==============================] - 128s 273ms/step - loss: 0.0527 - accuracy: 0.9834 - val_loss: 0.0482 -

In [31]:
import matplotlib.pyplot as plt  
from sklearn.datasets import make_classification
from sklearn.metrics import plot_confusion_matrix
from sklearn.svm import SVC

In [49]:
# Predicting from test data
y_pred=model.predict_classes(X_test)

#Creating confusion matrix
confusion_matrix(y_test,y_pred)
cm = metrics.confusion_matrix(y_test, y_pred)

In [41]:
#Checking for accuracy
accuracy_score(y_test,y_pred)

0.9856892129067099

In [42]:
# Creating classification report 
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      7777
           1       0.99      0.98      0.98      7037

    accuracy                           0.99     14814
   macro avg       0.99      0.99      0.99     14814
weighted avg       0.99      0.99      0.99     14814



In [43]:
# Creating bidirectional lstm model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100))) # Bidirectional LSTM layer
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 5000, 40)          400000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dropout_2 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 201       
Total params: 513,001
Trainable params: 513,001
Non-trainable params: 0
_________________________________________________________________
None


In [44]:
# Fitting the model
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
470/470 [==============================] - 238s 500ms/step - loss: 0.3311 - accuracy: 0.8533 - val_loss: 0.0819 - val_accuracy: 0.9732
Epoch 2/10
470/470 [==============================] - 235s 500ms/step - loss: 0.0468 - accuracy: 0.9864 - val_loss: 0.0473 - val_accuracy: 0.9868
Epoch 3/10
470/470 [==============================] - 238s 506ms/step - loss: 0.0245 - accuracy: 0.9931 - val_loss: 0.0419 - val_accuracy: 0.9878
Epoch 4/10
470/470 [==============================] - 236s 503ms/step - loss: 0.0218 - accuracy: 0.9945 - val_loss: 0.0406 - val_accuracy: 0.9890
Epoch 5/10
470/470 [==============================] - 236s 503ms/step - loss: 0.0155 - accuracy: 0.9966 - val_loss: 0.1260 - val_accuracy: 0.9559
Epoch 6/10
470/470 [==============================] - 237s 503ms/step - loss: 0.0467 - accuracy: 0.9842 - val_loss: 0.0528 - val_accuracy: 0.9869
Epoch 7/10
470/470 [==============================] - 237s 505ms/step - loss: 0.0142 - accuracy: 0.9960 - val_loss: 0.0313 -

In [46]:
# Predicting from test dataset
y_pred1=model1.predict_classes(X_test)

Confusion matrix
cm = metrics.confusion_matrix(y_test, y_pred1)

In [47]:
#Calculating Accuracy score
accuracy_score(y_test,y_pred1)

0.9869042797353854

In [48]:
# Creating classification report 
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      7777
           1       0.99      0.98      0.99      7037

    accuracy                           0.99     14814
   macro avg       0.99      0.99      0.99     14814
weighted avg       0.99      0.99      0.99     14814

